class SystemInfo:
    def __init__(self, prmtop: str, inpcrd: str, runMin: str = ..., runMd: str = ...) -> None: ...
    def getNprotein(self) -> int: ...
    def getnDna(self) -> int: ...
    def getnRna(self) -> int: ...
    def getnLipid(self) -> int: ...
    def getnUnKnown_(self) -> int: ...
    def getnCharmmWater_(self) -> int: ...
    def getnWater(self) -> int: ...
    def getnCarbo(self) -> int: ...
    def getHasCharmmWater(self) -> bool: ...
    def getHasOrthoBox(self) -> bool: ...
    def getRunMin(self) -> str: ...
    def getRunMd(self) -> str: ...
    def getHeavyMask(self) -> str: ...
    def getBackBoneMask(self) -> str: ...

class Min:
    def __init__(self, name: str, systemInfo: SystemInfo, ref: str, refc: str, irest: bool = ..., restraintmask: str = ..., restraint_wt: float = ..., cut: float = ..., nTmin: int = ..., maxCyc: int = ..., nCyc: int = ..., nTwx: int = ..., nTpr: int = ..., nTwr: int = ...) -> None: ...
    def setCut(self, cut: float) -> Min: ...
    def setNTpr(self, ntpr: int) -> Min: ...
    def setNTwr(self, ntwr: int) -> Min: ...
    def setNTwx(self, ntwx: int) -> Min: ...
    def setMaxCyc(self, maxcyc: int) -> Min: ...
    def setNCyc(self, cyc: int) -> Min: ...
    def setNTim(self, ntmin: int) -> Min: ...
    def setRestraintMask(self, restraintMask: str) -> Min: ...
    def Run(self) -> None: ...

class Md:
    def __init__(self, name: str, systemInfo: SystemInfo, ref: str, refc: str, irest: bool = ..., temp: float = ..., restraintmask: str = ..., restraint_wt: float = ..., nstlim: int = ..., cut: float = ..., ntb: int = ..., ntc: int = ..., ntf: int = ..., tautp: float = ..., taup: float = ..., mcbarint: int = ..., gamma_ln: float = ..., dt: float = ..., nscm: int = ..., ntwx: int = ..., ntpr: int = ..., ntwr: int = ...) -> None: ...
    def setCut(self, cut: float) -> Md: ...
    def setTemp(self, temp: float) -> Md: ...
    def setNTpr(self, ntpr: int) -> Md: ...
    def setNTwx(self, ntwx: int) -> Md: ...
    def setNTwr(self, ntwr: int) -> Md: ...
    def setNstLim(self, nstlim: int) -> Md: ...
    def setIrest(self, irest: bool) -> Md: ...
    def setTautp(self, tautp: float) -> Md: ...
    def settaup(self, taup: float) -> Md: ...
    def setMcbarint(self, mcbarint: int) -> Md: ...
    def setGammaLn(self, gamma_ln: float) -> Md: ...
    def setDt(self, dt: float) -> Md: ...
    def setNscm(self, nscm: int) -> Md: ...
    def setNtx(self, ntx: int) -> Md: ...
    def setNtc(self, ntc: int) -> Md: ...
    def setNtf(self, ntf: int) -> Md: ...
    def setNtb(self, ntb: int) -> Md: ...
    def setBarostat(self, baroType: str) -> Md: ...
    def setThermostat(self, thermoType: str) -> Md: ...
    def setRestraintMask(self, restraintMask: str) -> Md: ...
    def Run(self) -> None: ...

class Nvt(Md):
    def __init__(self, name: str, systemInfo: SystemInfo, ref: str, refc: str, irest: bool = ..., temp: float = ..., restraintmask: str = ..., restraint_wt: float = ..., nstlim: int = ..., cut: float = ..., ntc: int = ..., ntf: int = ..., tautp: float = ..., gamma_ln: float = ..., dt: float = ..., nscm: int = ..., ntwx: int = ..., ntpr: int = ..., ntwr: int = ...) -> None: ...
    def setCut(self, cut: float) -> Nvt: ...
    def setTemp(self, temp: float) -> Nvt: ...
    def setNTpr(self, ntpr: int) -> Nvt: ...
    def setNTwx(self, ntwx: int) -> Nvt: ...
    def setNTwr(self, ntwr: int) -> Nvt: ...
    def setNstLim(self, nstlim: int) -> Nvt: ...
    def setIrest(self, irest: bool) -> Nvt: ...
    def setTautp(self, tautp: float) -> Nvt: ...
    def setGammaLn(self, gamma_ln: float) -> Nvt: ...
    def setDt(self, dt: float) -> Nvt: ...
    def setNscm(self, nscm: int) -> Nvt: ...
    def setNtx(self, ntx: int) -> Nvt: ...
    def setNtc(self, ntc: int) -> Nvt: ...
    def setNtf(self, ntf: int) -> Nvt: ...
    def setNtb(self, ntb: int) -> Nvt: ...
    def setThermostat(self, thermoType: str) -> Nvt: ...
    def setRestraintMask(self, restraintMask: str) -> Nvt: ...
    def Run(self) -> None: ...

class Npt(Md):
    def __init__(self, name: str, systemInfo: SystemInfo, ref: str, refc: str, irest: bool = ..., temp: float = ..., restraintmask: str = ..., restraint_wt: float = ..., nstlim: int = ..., cut: float = ..., ntc: int = ..., ntf: int = ..., tautp: float = ..., taup: float = ..., mcbarint: int = ..., gamma_ln: float = ..., dt: float = ..., nscm: int = ..., ntwx: int = ..., ntpr: int = ..., ntwr: int = ...) -> None: ...
    def setCut(self, cut: float) -> Npt: ...
    def setTemp(self, temp: float) -> Npt: ...
    def setNTpr(self, ntpr: int) -> Npt: ...
    def setNTwx(self, ntwx: int) -> Npt: ...
    def setNTwr(self, ntwr: int) -> Npt: ...
    def setNstLim(self, nstlim: int) -> Npt: ...
    def setIrest(self, irest: bool) -> Npt: ...
    def setTautp(self, tautp: float) -> Npt: ...
    def setTaup(self, taup: float) -> Npt: ...
    def setMcbarint(self, mcbarint: int) -> Npt: ...
    def setGammaLn(self, gamma_ln: float) -> Npt: ...
    def setDt(self, dt: float) -> Npt: ...
    def setNscm(self, nscm: int) -> Npt: ...
    def setNtx(self, ntx: int) -> Npt: ...
    def setNtc(self, ntc: int) -> Npt: ...
    def setNtf(self, ntf: int) -> Npt: ...
    def setBarostat(self, baroType: str) -> Npt: ...
    def setThermostat(self, thermoType: str) -> Npt: ...
    def setRestraintMask(self, restraintMask: str) -> Npt: ...
    def Run(self) -> None: ...

class GaMd(Npt):
    def __init__(self, name: str, systemInfo: SystemInfo, ref: str, refc: str, irest: bool = ..., temp: float = ..., restraintmask: str = ..., restraint_wt: float = ..., nstlim: int = ..., cut: float = ..., ntc: int = ..., ntf: int = ..., tautp: float = ..., taup: float = ..., mcbarint: int = ..., gamma_ln: float = ..., dt: float = ..., nscm: int = ..., ntwx: int = ..., ntpr: int = ..., ntwr: int = ..., igamd: int = ..., ie: int = ..., iep: int = ..., ied: int = ..., ntcmdprep: int = ..., ntcmd: int = ..., ntebprep: int = ..., nteb: int = ..., ntave: int = ..., irest_gamd: int = ..., sigma0P: float = ..., sigma0D: float = ..., timask1: str = ..., scmask1: str = ...) -> None: ...
    def setCut(self, cut: float) -> GaMd: ...
    def setTemp(self, temp: float) -> GaMd: ...
    def setNTpr(self, ntpr: int) -> GaMd: ...
    def setNTwx(self, ntwx: int) -> GaMd: ...
    def setNTwr(self, ntwr: int) -> GaMd: ...
    def setNstLim(self, nstlim: int) -> GaMd: ...
    def setIrest(self, irest: bool) -> GaMd: ...
    def setTautp(self, tautp: float) -> GaMd: ...
    def setTaup(self, taup: float) -> GaMd: ...
    def setMcbarint(self, mcbarint: int) -> GaMd: ...
    def setGammaLn(self, gamma_ln: float) -> GaMd: ...
    def setDt(self, dt: float) -> GaMd: ...
    def setNscm(self, nscm: int) -> GaMd: ...
    def setNtx(self, ntx: int) -> GaMd: ...
    def setNtc(self, ntc: int) -> GaMd: ...
    def setNtf(self, ntf: int) -> GaMd: ...
    def setBarostat(self, baroType: str) -> GaMd: ...
    def setThermostat(self, thermoType: str) -> GaMd: ...
    def setRestraintMask(self, restraintMask: str) -> GaMd: ...
    def setIGaMd(self, igamd: int) -> GaMd: ...
    def setIe(self, ie: int) -> GaMd: ...
    def setIep(self, iep: int) -> GaMd: ...
    def setIed(self, ied: int) -> GaMd: ...
    def setNtcmdprep(self, ntcmdprep: int) -> GaMd: ...
    def setNteb(self, nteb: int) -> GaMd: ...
    def setNtave(self, ntave: int) -> GaMd: ...
    def setIrest_gamd(self, irest_gamd: int) -> GaMd: ...
    def setSigma0P(self, sigma0P: float) -> GaMd: ...
    def setSigmaOD(self, sigma0D: float) -> GaMd: ...
    def setTimask1(self, timask1: str) -> GaMd: ...
    def setScmask1(self, scmask1: str) -> GaMd: ...
    def Run(self) -> None: ...
