{% set version = load_file_regex(
    load_file='../AmberMDrun/version.py',
    regex_pattern="__version__\\s*=\\s*['\\\"]([^'\\\"]+)['\\\"]"
).group(1) %}

package:
  name: ambermdrun
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - "{{ compiler('cxx') }}"
  host:
    - cmake
    - ninja
    - python
    - pip !=22.1.0
    - setuptools
    - wheel
  run:
    - python
    - pandas >=1.0.0

test:
  imports:
    - AmberMDrun

about:
  summary: A scripting tool for running Amber MD in an easy way
  license: MIT
  license_family: MIT
  license_file: LICENSE
  home: https://github.com/9527567/AmberMDrun
  dev_url: https://github.com/9527567/AmberMDrun
