{% set version = environ.get('AMBERMDRUN_VERSION', '0.1.0') %}

package:
  name: ambermdrun
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - "{{ compiler('cxx') }}"
  host:
    - cmake
    - ninja
    - python
    - pip !=22.1.0
    - setuptools <77
    - wheel
  run:
    - python >=3.9,<3.15
    - pandas >=1.0.0

test:
  imports:
    - AmberMDrun

about:
  summary: A scripting tool for running Amber MD in an easy way
  license: MIT
  license_family: MIT
  license_file: LICENSE
  home: https://github.com/9527567/AmberMDrun
  dev_url: https://github.com/9527567/AmberMDrun
