{% set data = load_setup_py_data() %}

package:
  name: ambermdrun
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - cmake
    - ninja
    - python
    - setuptools
  host:
    - python
    - pip !=22.1.0
  run:
    - python
    - pandas >=1.0.0

outputs:
  - name: ambermdrun
    files:
      - AmberMDrun/
      - AmberMDrun-*

about:
  summary: A scripting tool for running Amber MD in an easy way
  license: MIT
  license_family: MIT
  license_file: LICENSE
  home: https://github.com/9527567/AmberMDrun
  dev_url: https://github.com/9527567/AmberMDrun
